# BUILDING STAGE
FROM node:22.17-alpine AS builder

# Set working dir on Docker
WORKDIR /app

# Copy to container
COPY package*.json ./
COPY tsconfig*.json ./

# Install dependencies
RUN npm ci

# Copy everything
COPY . .

# Build JS files
RUN npm run build

# -------------------
# -------------------
# DEV STAGE
FROM node:22.17-alpine AS dev

WORKDIR /app

# Copy everything from builder
COPY --from=builder /app ./

# Expose port
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]

# -------------------
# -------------------
# PROD STAGE
FROM nginx:alpine AS production

WORKDIR /app
COPY package*.json ./
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy JS files built from TS
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose the port that the app listens to
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]