# docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build

services:
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
      target: production
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend