# docker compose -f docker-compose.yml up --build

services:
  backend:
    build:
      context: ./server #Dockerfile location
      dockerfile: dockerfile
      target: production
    env_file:
      - .env
    depends_on: # Wait for database to start first
      - database

  database:
    image: postgres:17
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:

networks:
  default:
    name: internal-sock
    external: true