#docker compose -f docker-compose.test-db.yml up

version: "3.9"
services:
  database_test:
    image: postgres:17
    restart: always
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20
    env_file:
      - .env.test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data_test
    ports:
      - "5433:5432" # host 5433 -> 5432
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data_test:

networks:
  prisma-network:
    name: prisma-network
