# script for composing dev
# docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build

services:
  backend:
    build: 
      context: ./server
      dockerfile: dockerfile
      target: dev
    ports:
      - 5000:5000
    volumes:
      - ./server/src:/app/src

  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
      target: dev
    ports:
      - "5173:5173"
    environment:
    # Still need this cus it's npm run dev on TS files -> env file isnt baked into the code
      - VITE_API_URL=http://localhost:5000 
    volumes:
      - ./client:/app
      - /app/node_modules

  database:
    ports:
      - "5432:5432"

  prisma-studio:
    image: node:lts-alpine3.17
    working_dir: /app
    volumes:
      - ./server:/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - database
      - backend
