# docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build

services:
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
      target: production
      # Need this to "bake" the env in during build time, not run time
      args:
        - VITE_API_URL=http://localhost:5000/api
    ports:
      - "80:80"
    depends_on:
      - backend
  
  database:
    ports:
      - "5432:5432"

  backend:
    ports:
      - "5000:5000"
