services:
  backend:
    build:
      context: ./server #Dockerfile location
      dockerfile: dockerfile
      target: production
    ports:
      - "5000:5000" # Host port 5000 → Container port 5000
    env_file:
      - .env
    depends_on: # Wait for database to start first
      - database
    networks:
      - prisma-network

  database:
    image: postgres:17
    restart: always
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 20
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Host port 5432 → Container port 5432
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
networks:
  prisma-network:
    name: prisma-network