# docker compose -f docker-compose.yml -f docker-compose.prod.yml up --build

services:
# No Vite env needed because npm run build alrdy baked the .env file into the container's dist
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
      target: production
    ports:
      - "80:80"
    depends_on:
      - backend
  
  database:
    ports:
      - "5432:5432"

  backend:
    ports:
      - "5000:5000"
