###
GET http://localhost:5000


### POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "BalloonBoy",
    "password": "Password123!"
}
### 

POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "User2",
    "password": "Password1234!"
}

### POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "BalloonBoy",
    "password": "123123123"
}
### 

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "User2",
    "password": "Password1234!"
}
### 

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "User2",
    "password": "32132132"
}






### Fetch all todos GET /LOGS (protected)
GET http://localhost:5000/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1NDUwOTk4LCJleHAiOjE3NTU0NTQ1OTh9.xgdWQViIqXCe19pQc-nNr0W829jdDq8Wf5lXF79lEuM

### Create a log entry  POST /LOGS (protected)
POST http://localhost:5000/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1NDUwOTk4LCJleHAiOjE3NTU0NTQ1OTh9.xgdWQViIqXCe19pQc-nNr0W829jdDq8Wf5lXF79lEuM
Content-Type: application/json

{
    "mediaId": 2,
    "status": "Watching",
    "rating": 50,
    "notes": "This is a note"
}





### Fetch all medias for user GET /MEDIA (protected)
GET http://localhost:5000/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1NDUwOTk4LCJleHAiOjE3NTU0NTQ1OTh9.xgdWQViIqXCe19pQc-nNr0W829jdDq8Wf5lXF79lEuM

### Create new media entry  POST /MEDIA (protected)
POST http://localhost:5000/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1NDUwOTk4LCJleHAiOjE3NTU0NTQ1OTh9.xgdWQViIqXCe19pQc-nNr0W829jdDq8Wf5lXF79lEuM
Content-Type: application/json

{
    "title": "1984", 
    "mediaType": {
        "name": "Books"
    }, 
    "creator": "George Orwell", 
    "year": 1984, 
    "metadata": {
        "pageCount": 20,
        "version": 2
    }
}
###

POST http://localhost:5000/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU1NDQ1OTE3LCJleHAiOjE3NTU0NDk1MTd9.nu6l80gXltnYO0X3SQEsgzGV3waZnw2mzppsLLrBOrw
Content-Type: application/json

{
    "title": "Wow", 
    "mediaType": {
        "name": "music"
    }, 
    "creator": "Cardi", 
    "year": 1984, 
    "metadata": {
        "tracks": 10
    }
}

### Edit media entry PUT /MEDIA/:ID (protected)
PUT http://localhost:5000/media/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU1NDQ1OTE3LCJleHAiOjE3NTU0NDk1MTd9.nu6l80gXltnYO0X3SQEsgzGV3waZnw2mzppsLLrBOrw
Content-Type: application/json

{
    "title": "Wow", 
    "mediaType": {
        "id": 2
    }, 
    "creator": "Cardi Aays", 
    "year": 1984, 
    "metadata": {
        "tracks": 9
    }
}

### Delete media entry DELETE /MEDIA/:ID (protected)
DELETE http://localhost:5000/media/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzU1NDQ1OTE3LCJleHAiOjE3NTU0NDk1MTd9.nu6l80gXltnYO0X3SQEsgzGV3waZnw2mzppsLLrBOrw
Content-Type: application/json

{
    "confirm": false
}



### Fetch all media-types the user has GET /MEDIA-TYPE (protected)
GET http://localhost:5000/media-type
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM
### Create new media type POST/MEDIA-TYPE (protected)
POST http://localhost:5000/media-type
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM
Content-Type: application/json

{
    "name": "    MUSIC      "
}

### Delete a media-type DELETE /MEDIA-TYPE/:NAME (protected)
DELETE http://localhost:5000/media-type/book
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM

### Update a media-type PUT /MEDIA-TYPE/:NAME (protected)
PUT http://localhost:5000/media-type/gaMING
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM
Content-Type: application/json

{
    "newName": "MUSIC      "
}