###
GET http://localhost:5000


### POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "BalloonBoy",
    "password": "123123123"
}
### 

POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "User2",
    "password": "321321321"
}

### POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "BalloonBoy",
    "password": "123123123"
}
### 

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "User2",
    "password": "321321321"
}
### 

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "User2",
    "password": "32132132"
}






### Fetch all todos GET /LOGS (protected)
GET http://localhost:5000/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjM2NTQ2LCJleHAiOjE3NTUyNDAxNDZ9.nbSBLtwaI5Ph6yrGL8obWX9XrV2eF3I-G9MhN1cycF8

###
POST http://localhost:5000/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjM2NTQ2LCJleHAiOjE3NTUyNDAxNDZ9.nbSBLtwaI5Ph6yrGL8obWX9XrV2eF3I-G9MhN1cycF8
Content-Type: application/json

{
    
}





### Fetch all medias for user GET /MEDIA (protected)
GET http://localhost:5000/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM
### Create a new media POST /MEDIA (protected)
POST http://localhost:5000/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM
Content-Type: application/json

{
    "title": "1984", 
    "mediaType": {
        "name": "Books"
    }, 
    "creator": "George Orwell", 
    "year": 1984, 
    "metadata": {
        "pageCount": 20,
        "version": 2
    }
}
###

POST http://localhost:5000/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM
Content-Type: application/json

{
    "title": "Wow", 
    "mediaType": {
        "name": "music"
    }, 
    "creator": "Cardi", 
    "year": 1984, 
    "metadata": {
        "tracks": 10
    }
}

### Edit media entry PUT /MEDIA/:ID (protected)
PUT http://localhost:5000/media/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM
Content-Type: application/json

{
    "title": "Wow", 
    "mediaType": {
        "id": 2
    }, 
    "creator": "Cardi Aays", 
    "year": 1984, 
    "metadata": {
        "tracks": 9
    }
}

### Delete media entry DELETE /MEDIA/:ID (protected)
DELETE http://localhost:5000/media/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM
Content-Type: application/json

{
    "confirm": false
}



### Fetch all media-types the user has GET /MEDIA-TYPE (protected)
GET http://localhost:5000/media-type
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM
### Create new media type POST/MEDIA-TYPE (protected)
POST http://localhost:5000/media-type
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM
Content-Type: application/json

{
    "name": "    MUSIC      "
}

### Delete a media-type DELETE /MEDIA-TYPE/:NAME (protected)
DELETE http://localhost:5000/media-type/book
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM

### Update a media-type PUT /MEDIA-TYPE/:NAME (protected)
PUT http://localhost:5000/media-type/gaMING
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MjgyOTg1LCJleHAiOjE3NTUyODY1ODV9.wWtWkamtVKS4NAzQQ5nAMZ6a7upoi0llfkMxADvQbdM
Content-Type: application/json

{
    "newName": "MUSIC      "
}