###
GET http://localhost:5000


### POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "BalloonBoy",
    "password": "Password123!",
    "displayName": "Ball Boy"
}
### 

POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "Use",
    "password": "Password1234"
}

### POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "TestUser",
    "password": "Password123!"
}
### 

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "User2",
    "password": "Password1234!"
}
### 

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "system",
    "password": "System1000KG!"
}






### Fetch all todos GET /LOGS (protected)
GET http://localhost:5000/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI

### Create a log entry  POST /LOGS (protected)
POST http://localhost:5000/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI
Content-Type: application/json

{
    "mediaId": 4,
    "status": "in progress",
    "rating": 50,
    "notes": "This is a noteD"
}

### Update a log entry  PUT /LOGS/:ID (protected)
PUT http://localhost:5000/logs/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI
Content-Type: application/json

{
    "status": "Completed",
    "rating": 1000,
    "notes": "WIBIBILY WOBBLYLY HAHAHAH HOHJOHOHOHOHOH OAHAHWHSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS ASDASDASDJHFGJFJFJGDAFADFAFADFDSSSSSSSSSSSSSSSSSSSSSSSSSSSS IAMINVICINBLE ALKSLKDINVISIBLE INVINCIBLE"
}

### DELETE A LOG DELETE /LOGS/:ID (protected)
DELETE  http://localhost:5000/logs/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI
Content-Type: application/json

{
    "confirm": false
}

### Fetch all medias for user GET /MEDIA (protected)
GET http://localhost:5000/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI

### Create new media entry  POST /MEDIA (protected)
POST http://localhost:5000/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI
Content-Type: application/json

{
    "title": "198", 
    "mediaType": {
        "name": "books"
    },
    "creator": "George Orwell", 
    "year": 1984, 
    "metadata": {
        "pageCount": 20,
        "version": 2
    }
}
###

POST http://localhost:5000/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI
Content-Type: application/json

{
    "title": "Won", 
    "mediaType": {
        "name": "music"
    }, 
    "creator": "Cardi", 
    "year": 1984, 
    "metadata": {
        "tracks": 10
    }
}

### Edit media entry PUT /MEDIA/:ID (protected)
PUT http://localhost:5000/media/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI
Content-Type: application/json

{
    "title": "Wow", 
    "mediaType": {
        "name": "book"
    }, 
    "creator": "Cardi Aays", 
    "year": 1984, 
    "metadata": {
        "tracks": 9
    }
}

### Delete media entry DELETE /MEDIA/:ID (protected)
DELETE http://localhost:5000/media/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI
Content-Type: application/json

{
    "confirm": false
}



### Fetch all media-types the user has GET /MEDIA-TYPE (protected)
GET http://localhost:5000/media-type
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI
### Create new media type POST/MEDIA-TYPE (protected)
POST http://localhost:5000/media-type
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI
Content-Type: application/json

{
    "name": "   gamES      "
}

### Delete a media-type DELETE /MEDIA-TYPE/:NAME (protected)
DELETE http://localhost:5000/media-type/gaming
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI
Content-Type: application/json

{
    "confirm": false
}
### Update a media-type PUT /MEDIA-TYPE/:NAME (protected)
PUT http://localhost:5000/media-type/gamesss
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI
Content-Type: application/json

{
    "newName": "Gaming      "
}
###
PUT http://localhost:5000/media-type/lonelines
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU3MDcwMDc1LCJleHAiOjE3NTcwNzM2NzV9._vPcMPvrwFpJuNlKskt2qRTb_WFFb3zOwCFgH0P3NYI
Content-Type: application/json

{
    "newName": "games      "
}