###
POST http://localhost:5000/healthz/


### POST /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "BalloonBoy",
    "password": "Password123!",
    "displayName": "Ball Boy"
}
### 

POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "Use",
    "password": "Password1234"
}

### POST /AUTH/LOGIN
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "demo",
    "password": "Demo123!!!"
}
### 

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "BalloonBoy",
    "password": "Password123!"
}
### 

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "system",
    "password": "System1000KG!"
}






### Fetch all todos GET /LOGS (protected)
GET http://localhost:5000/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU

### Create a log entry  POST /LOGS (protected)
POST http://localhost:5000/logs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "mediaId": 29,
    "status": "in progress",
    "rating": 50,
    "notes": 12
}

### Update a log entry  PUT /LOGS/:ID (protected)
PUT http://localhost:5000/logs/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "status": "Completed",
    "rating": 1000,
    "notes": "WIBIBILY WOBBLYLY HAHAHAH HOHJOHOHOHOHOH OAHAHWHSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS ASDASDASDJHFGJFJFJGDAFADFAFADFDSSSSSSSSSSSSSSSSSSSSSSSSSSSS IAMINVICINBLE ALKSLKDINVISIBLE INVINCIBLE"
}

### DELETE A LOG DELETE /LOGS/:ID (protected)
DELETE  http://localhost:5000/logs/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "confirm": false
}

### Fetch all medias for user GET /MEDIA (protected)
GET http://localhost:5000/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU

### Create new media entry  POST /MEDIA (protected)
POST http://localhost:5000/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "title": "198", 
    "mediaType": {
        "name": "books"
    },
    "creator": "George Orwell", 
    "year": 1984, 
    "metadata": {
        "pageCount": 20,
        "version": 2
    }
}
###

POST http://localhost:5000/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "title": "WonWon", 
    "mediaType": {
        "id": 2, 
        "name": "music",
        "userId": 1,
        "created_at": "20"
    }, 
    "description": "hello",
    "source": "what",
    "sourceId": "hiwejw",
    "sourceRating": 100,
    "ratingsCount": 1000,
    "imageUrl": "hajkhsd",
    "creator": "Cardi", 
    "year": "abcd", 
    "metadata": {
        "tracks": 10
    }
}

### Edit media entry PUT /MEDIA/:ID (protected)
PUT http://localhost:5000/media/29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "title": "WonWon", 
    "mediaType": {
        "name": "music"
    }, 
    "description": "hello",
    "source": "what",
    "sourceId": "hiwejw",
    "sourceRating": 100,
    "ratingsCount": 1000,
    "imageUrl": "hajkhsd",
    "creator": "Cardi", 
    "year": 1984, 
    "metadata": {
        "tracks": 10
    }
}

### Delete media entry DELETE /MEDIA/:ID (protected)
DELETE http://localhost:5000/media/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "confirm": false
}



### Fetch all media-types the user has GET /MEDIA-TYPE (protected)
GET http://localhost:5000/media-type
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
### Create new media type POST/MEDIA-TYPE (protected)
POST http://localhost:5000/media-type
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "name": "   gamES      "
}

### Delete a media-type DELETE /MEDIA-TYPE/:NAME (protected)
DELETE http://localhost:5000/media-type/gaming
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "confirm": false
}
### Update a media-type PUT /MEDIA-TYPE/:NAME (protected)
PUT http://localhost:5000/media-type/gamesss
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "newName": "Gaming      "
}
###
PUT http://localhost:5000/media-type/lonelines
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "newName": "games      "
}


### SEARCH
### Search for books GET /BOOKS?=q
GET http://localhost:5000/search/books?q=ocean
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Accept: application/json

### Search for tracks GET /MUSIC/TRACKS?=q
GET http://localhost:5000/search/music/albums?q=pain-to-power
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Accept: application/json

### API KEY
### Fetch all Api keys for user GET /API-KEY
GET http://localhost:5000/api-key
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU


### Add key POST /API-KEY
POST  http://localhost:5000/api-key
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "key": "033bb2400bbc6f8ddf55b9c8f998cdfb",
    "service": "lastfm"
}

### Update key PUT /API-KEY
PUT  http://localhost:5000/api-key
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "key": "API key 2",
    "service": "google_book"
}

###
DELETE  http://localhost:5000/api-key
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzY0NDMwNzk4LCJleHAiOjE3NjQ0MzQzOTh9.Myhs0iwQInjmrMsa5g4F6q2OywU31OBxML8DeKo0WUU
Content-Type: application/json

{
    "service": "google_books"
}
