name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: mydb_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d mydb_test"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=20

    env:
      # Non-secret test env
      NODE_ENV: test
      RATE_LIMIT_ENABLED: false
      PORT: 5000
      POSTGRES_DB: mydb_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password

      # Secrets
      GOOGLE_BOOKS_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}
      LASTFM_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}
      JWT_KEY_SECRET: ${{ secrets.JWT_KEY_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
      DEMO_USER_PASSWORD: ${{ secrets.DEMO_USER_PASSWORD }}
      SYSTEM_USER_PASSWORD: ${{ secrets.SYSTEM_USER_PASSWORD }}

      DATABASE_URL: postgresql://test_user:test_password@localhost:5432/mydb_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: ./server
        run: npm ci

      - name: Run Migrations
        working-directory: ./server
        run: npx prisma migrate deploy

      - name: Run Tests
        working-directory: ./server
        run: npm run test
