name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
      - "client/**"
  pull_request:

jobs:
  backend-lint-and-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Backend Checks
        working-directory: ./server
        run: |
          npm ci
          npx tsc --noEmit
          npm run lint
    
  frontend-lint-and-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Frontend Checks
        working-directory: ./client
        run: |
          npm ci
          npm run lint
          npm run build
  
  security-audit-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create dummy env file
        run: touch .env

      - name: Build Frontend (Dev)
        # We need .dev.yaml because "frontend" is defined there
        run: docker compose -f docker-compose.yml -f docker-compose.dev.yml build frontend

      - name: Audit Frontend
        run: docker compose -f docker-compose.yml -f docker-compose.dev.yml run --rm frontend npm audit
  
  security-audit-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create dummy env file
        run: touch .env
        
      - name: Build Backend (Prod)
        run: docker compose -f docker-compose.yml build backend

      - name: Audit Backend
        # --no-deps: Don't start the database
        run: docker compose -f docker-compose.yml run --rm --no-deps backend npm audit

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: mydb_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user -d mydb_test"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=20

    env:
      # Non-secret test env
      NODE_ENV: test
      RATE_LIMIT_ENABLED: false
      REGISTER_KEY: "register_key"
      PORT: 5000
      POSTGRES_DB: mydb_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password

      # Secrets
      GOOGLE_BOOKS_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}
      LASTFM_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}
      JWT_KEY_SECRET: ${{ secrets.JWT_KEY_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
      DEMO_USER_PASSWORD: ${{ secrets.DEMO_USER_PASSWORD }}
      SYSTEM_USER_PASSWORD: ${{ secrets.SYSTEM_USER_PASSWORD }}

      DATABASE_URL: postgresql://test_user:test_password@localhost:5432/mydb_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install backend dependencies
        working-directory: ./server
        run: npm ci
        
      - name: Type Check
        working-directory: ./server
        run: npx tsc --noEmit

      - name: Run Migrations
        working-directory: ./server
        run: npx prisma migrate deploy

      - name: Run Tests
        working-directory: ./server
        run: npm run test
