name: Deploy Frontend

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and build
        run: |
          cd client
          npm install
          npm run build
          cp dist/index.html dist/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: client/dist
          branch: gh-pages
